stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/
    
variables:
  CI: ""

build:
  stage: build
  image: node:11
  script:
    - npm install --progress=false
    - npm run build

deploy:
  stage: deploy
  image: ruby:2.3
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install faraday -v 1.0.1
    - gem install dpl
    - dpl --provider=heroku --app=assig4-frontend --api-key=$HEROKU_API_KEY --skip_cleanup
  environment:
    name: staging
    url: https://assig4-frontend.herokuapp.com/
  only:
    - docker-production
